### ISSUE TITLE
Input data shape

### ISSUE THREAD

**Issue by StefanReuscher** [cma2015/DeepGS#3]
Dear Authors,

Thanks for this implementation of CNNs. I am sure it will attract more attention soon.

I used your paper and the R package to teach myself DeepGS and DL in general. I can understand most of your code but one thing is really unclear to me. I have been running the examples and then went into the source for `train_deepGSModel()` and I am puzzled. Why do you reshape the input data the way you do ? 

```
# reshape input matrix
dim(trainMat) <- c(markerImage[1], markerImage[2], 1, ncol(trainMat))
dim(validMat) <- c(markerImage[1], markerImage[2], 1, ncol(validMat))
# output is a 4D array

```
Why add two dimensions of length 1 ? I also cannot imagine a case where one individual is not in one row ? I havent tried to run this with just two dims as input but I probably should. 

From what I learned DL is very dependent on the data representation, so I feel this is not trivial. In addition, what would be your suggestion for actual base data (A,C,G,T or even IUPAC bases).

Best Regards,

Stefan

**Comment by mawenlong2016** [comment]
Thank you for your attention.
The model we trained is based on each single individual. 
We trained the DeepGS model by extracting features from a specific sample's genotypic markers.
So the 4-dimension represent the managing of the the input data to fit for our demand.

The first dimension represents the row number of the genotypic markers.
The second dimension represents the column number of the genotypic markers.
The third dimension represents treated individual(s) one time (in our current model, we extracted one single individual for one time, so the third dimension is set to 1).
The fourth dimension represents the number of the trained samples.

The genotypic markers we used is DArT format, including 0 or 1 indicates the presence or absence of an allele. Then, for each individual, the format of the genotypic markers is 1-dimensional.
This is why we reshape the input matrix to 1-n-1-N format (the n represents the number of genotypic markers, the N represents the number of trained samples).

Another reason for the 4-dimension reshaped is that we reserved our DeepGS model's extension for fitting more conditions of the format of the genotypic matrix and the handled sample(s) one time.

As your suggestion, when we get a genotypic matrix based on the actual base data (A, C, G, T), we may  transformed the A to (1,0,0,0), C to (0,1,0,0), G to (0,0,1,0) and T to (0,0,0,1).
Then the 4D array should be 4-n-1-N.

In the future, we plan to improve our model to handle more samples one time. At that time, the third dimension will be m(m >=1).

Hope I can solve your puzzles through the above explains.
If you still puzzled, you can update and we will discuss further.

 Best wishes.

**Comment by StefanReuscher** [comment]
Thank you for your prompt answer, it help alot. But I still have a hard time to figure out the dimensions.

### The following is with regard to the reshaped matrix, could you clarify ?:

- The first dimension represents the actual genotype. It is of length one because its either absence or presence of the DArT marker (0|1). It can be expanded to length 4 to 1hot encode bases.

- The second dimension is the number of markers per individual

- The third dimension is allows for replication in the individuals, if your field experiment included replications. Length = number of replicate individuals

- The forth dimension is the number of non-replicated individuals.

Best Regards,

Stefan

**Comment by mawenlong2016** [comment]
For example, I have a reference population with a data set of 100 * 10, where the 100 represents the marker number, the 10 represents the sample number.

The genotypic format is numeric (e.g., 0 or 1, just as in the example data, or 1, 2, 3, 4 for A, T, C, G). 
Case 1: Regard the genotypic markers as a whole
1-100-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 1 * 100 genotypic markers

Case 2: Regard the genotypic markers as a relative rectangle (e.g., based on the LD, the adjacent markers related with each other, just as a picture, 1 * 100 vector can be transformed to 2 * 50, 10 * 10, ..., or other format.),
10-10-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 10 * 10 genotypic markers. 
Please note that the 10 * 10 rectangle is transformed from the 1 * 100 vector under the condition that the adjacent markers are related with each other.
We conserve the first and second dimensions to fit for further exploring the relations between the genotypic markers (e.g., LD or coexpression).

Case 3: The genotypic format is character (e.g., A, T, C, G to transform to (1,0,0,0), (0,1,0,0), (0,0,1,0), (0,0,0,1), just as what you understand).
4-100-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 4 * 100 genotypic markers.

Case 4: Handle 2 samples for one time (under exploring)
1-100-2-10
This means, the 10 samples handle 2 samples for one time to extract features from the 1 * 100 genotypic markers.
In our current version, we only support handling 1 sample for one time.
In the future, we will handle 2 or 3 or more samples for one time to fit for more conditions.

In summary, the first, second and third dimensions are extending to fit for further exploring. 
However, the forth dimension is fixed to the number of samples.

Scenario A:
The first dimension represents the actual genotype. It is of length one because its either absence or presence of the DArT marker (0|1). It can be expanded to length 4 to 1hot encode bases. 

The second dimension is the number of markers per individual

The third dimension is allows for cluster (1 or 2 or more for each gather) in the individuals, if your field experiment included similarity (e.g., separate the samples from different tissues or stages).

The forth dimension is the number of  individuals.

Scenario B:
The first dimension represents the row of the reshaped genotypic markers based on relations between the markers (e.g., LD or coexpression, just as a picture, adjacent markers are informative). 

The second dimension is the column of the reshaped genotypic markers based on relations between the markers. 

The third dimension is allows for cluster (1 or 2 or more for each gather) in the individuals, if your field experiment included similarity (e.g., separate the samples from different tissues or stages).

The forth dimension is the number of  individuals.

Hope I can solve your puzzles through the above explains.
If you still puzzled, you can update and we will discuss further.

Best wishes.

**Comment by mawenlong2016** [comment]
For example, I have a reference population with a data set of 100 * 10, where the 100 represents the marker number, the 10 represents the sample number.

The genotypic format is numeric (e.g., 0 or 1, just as in the example data, or 1, 2, 3, 4 for A, T, C, G).
Case 1: Regard the genotypic markers as a whole
1-100-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 1 * 100 genotypic markers

Case 2: Regard the genotypic markers as a relative rectangle (e.g., based on the LD, the adjacent markers related with each other, just as a picture, 1 * 100 vector can be transformed to 2 * 50, 10 * 10, ..., or other format.),
10-10-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 10 * 10 genotypic markers.
Please note that the 10 * 10 rectangle is transformed from the 1 * 100 vector under the condition that the adjacent markers are related with each other.
We conserve the first and second dimensions to fit for further exploring the relations between the genotypic markers (e.g., LD or coexpression).

Case 3: The genotypic format is character (e.g., A, T, C, G to transform to (1,0,0,0), (0,1,0,0), (0,0,1,0), (0,0,0,1), just as what you understand).
4-100-1-10
This means, the 10 samples handle 1 sample for one time to extract features from the 4 * 100 genotypic markers.

Case 4: Handle 2 samples for one time (under exploring)
1-100-2-10
This means, the 10 samples handle 2 samples for one time to extract features from the 1 * 100 genotypic markers.
In our current version, we only support handling 1 sample for one time.
In the future, we will handle 2 or 3 or more samples for one time to fit for more conditions.

In summary, the first, second and third dimensions are extending to fit for further exploring.
However, the forth dimension is fixed to the number of samples.

Scenario A:
The first dimension represents the actual genotype. It is of length one because its either absence or presence of the DArT marker (0|1). It can be expanded to length 4 to 1hot encode bases.

The second dimension is the number of markers per individual

The third dimension is allows for cluster (1 or 2 or more for each gather) in the individuals, if your field experiment included similarity (e.g., separate the samples from different tissues or stages).
In our current version, we only support handling 1 sample for one time.
In the future, we will handle 2 or 3 or more samples for one time to fit for more conditions.

The forth dimension is the number of individuals.

Scenario B:
The first dimension represents the row of the reshaped genotypic markers based on relations between the markers (e.g., LD or coexpression, just as a picture, adjacent markers are informative).

The second dimension is the column of the reshaped genotypic markers based on relations between the markers.

The third dimension is allows for cluster (1 or 2 or more for each gather) in the individuals, if your field experiment included similarity (e.g., separate the samples from different tissues or stages).
In our current version, we only support handling 1 sample for one time.
In the future, we will handle 2 or 3 or more samples for one time to fit for more conditions.


The forth dimension is the number of individuals.

Hope I can solve your puzzles through the above explains.
If you still puzzled, you can update and we will discuss further.

Best wishes.

**Comment by StefanReuscher** [comment]
Thanks for that very detailed answer. I really appreciate your effort. I understand now why there are four dimensions in the input data. Maybe you should put some of that text into readme or the R vignette.
I will definitely explore this arrangement a bit myself later.

All the best for your future research.

Greetings,

Stefan

**Comment by StefanReuscher** [comment]
I am not the author but I opened this issue. I think in this case presence or absence of an allele can be explained by the type of genetic markers used in the original study. They used Diversity Array Technology Marker (DArT). There should be enough literature around to explain this type of markers.

Greetings,

Stefan
